python-hyper/h11

- docs/source/_examples/myclient.py
- docs/source/api.rst
- docs/source/basic-usage.rst
- docs/source/changes.rst
- docs/source/supported-http.rst
- examples/curio-server.py
- examples/tiny-client-demo.py
- fuzz/README.rst
- fuzz/afl-server.py
- h11/_connection.py
- h11/_events.py
- h11/_receivebuffer.py
- h11/tests/helpers.py
- h11/tests/test_against_stdlib_http.py
- h11/tests/test_connection.py
- h11/tests/test_events.py
So now receive_data no longer returns a list of events; instead, it just
appends to the internal buffer, and then you have to call next_event to
get it. (So next_event is like the old receive_data(None).)
Maybe some other small changes snuck in, but that's the main one... this
involved a major rework of the code and docs.
The big advantage of this is that when trying to solve the really hard
problem of implementing a HTTP server that handles errors gracefully,
life is *much* simpler if you can take advantage of h11's knowledge of
the connection state. But with the old way of doing receive_data, you
might get back multiple events at once, and then while you're processing
the first event, conn.states is already updated to reflect the future
events you haven't processed yet. So you couldn't …
> Split receive_data into receive_data + next_event

- h11/_events.py
- h11/tests/test_events.py
> Use correct variable when telling the user which kwarg they forgot.

- h11/_events.py
- h11/_readers.py
- h11/_writers.py
- h11/tests/test_connection.py
- h11/tests/test_io.py
Though there is useless for "reason" on the Response.
but I think keep it still better than discard when using reader to parse it.
So I create a PR to keep the reason on Response.
I had following modification:
1. Retrieve reason when using reader to parse the incoming data by modify the regex
2. Give reason default value empty string if the server don't care about it and will send empty string to client.
BTW, I know almost every client/server don't care about it,
but for my usage, my friend and I had implement a proxy server that was using h11,
and try keep original message that generated by client/server to prevent any misunderstand.
I had another modification on h11 that is related to it: keep original header field case.
I will create another PR after your feedback if you like it. …
> Add reason at Response

- docs/source/api.rst
- docs/source/changes.rst
- h11/_connection.py
- h11/_state.py
- h11/_util.py
- h11/tests/test_util.py
This is a slightly wacky solution to #8. By "slightly wacky" I mean that contains the following line of code:
``` python
cls.__class__ = cls
```
Based on watching some of his talks I feel fairly confident that @dabeaz will appreciate this, but I am less certain about whether it's actually a good idea, so would appreciate comments ;-).
Actually, my main hesitation is that I'm not really sure whether doing table-based dispatch on the return value from `next_event` ever makes much sense -- in my experience so far, libraries usually have a pretty small and specific set of events that they're looking for at any given time. But maybe it's useful for those who like more declarative state-machine kind of approaches? And it's not a big deal to support; it's like 2 extra lines of code that don't …
> [rfc] Make sentinel objects instances of themselves

- docs/source/api.rst
- docs/source/changes.rst
- h11/_events.py
- h11/_readers.py
- h11/tests/helpers.py
- h11/tests/test_connection.py
> Non-working example of how we could expose chunk boundaries

- h11/_readers.py
- h11/tests/test_connection.py
Intended as at least a first step towards gh-23.
> More detailed errors when connection closed during message body

- h11/_headers.py
- h11/tests/test_headers.py
This should address #5 by raising an exception in the event of return characters in the header field value. I also added an exception for requests sending both Content-Length and Transfer-Encoding. [RFC 7230 3.3.2](https://tools.ietf.org/html/rfc7230#section-3.3.2) is pretty clear about that, so I felt like it was a safe call.
The only other major issues I can think of for cleaning up outgoing headers are already covered. Leading/trailing whitespace is taken care of by the `strip` on value, and trailing space on the name is handled the same way.
Let me know if I'm overlooking anything else.
> restrict newlines in header values

- h11/_abnf.py
- h11/_readers.py
- h11/tests/test_io.py
Examples:
* https://github.com/scrapy/scrapy/issues/345#issuecomment-281756036
* https://github.com/seanmonstar/httparse/issues/29
> Tolerate missing reason phrases

- h11/_connection.py
- h11/_headers.py
- h11/_util.py
- h11/tests/test_headers.py
`bytesify` shows up prominently in profiles (of a basic sync socket server
fed by netcat):
```
prof.prof% sort tottime
prof.prof% stats 10
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
200000    0.677    0.000    3.324    0.000 h11/_connection.py:226(_process_event)
680000    0.447    0.000    0.690    0.000 h11/_util.py:114(bytesify)
120000    0.438    0.000    0.438    0.000 {method 'sendall' of '_socket.socket' objects}
80000    0.437    0.000    1.319    0.000 h11/_events.py:26(__init__)
400000    0.435    0.000    1.175    0.000 h11/_headers.py:97(get_comma_header)
240000    0.351    0.000    1.299    0.000 h11/_connection.py:285(_respond_to_state_changes)
200000    0.337    0.000    0.412    0.000 h11/_state.py:256(_fire_state_triggered_transitions)
360000 …
```
> Remove slow bytesify calls when they are avoidable

- h11/_events.py
- h11/_headers.py
- h11/_readers.py
The parser already validates, so there's no need to do it twice, and
it's a bit expensive.
On my laptop, on the benchmark in bench/, I get:
CPython 3.5: ~4386 req/sec -> ~5141 req/sec = 17% speedup
PyPy 5.6.0: ~19311 req/sec -> ~21106 req/sec = 9% speedup
> Skip header validation for data parsed off the wire

- docs/source/changes.rst
- h11/_readers.py
- h11/tests/test_io.py
> Always return headers as bytes

- docs/source/changes.rst
- h11/_abnf.py
- h11/tests/test_events.py
- h11/tests/test_headers.py
- h11/tests/test_io.py
The RFC says we should reject any header value that contains control
characters. But apparently in the real world, you have to both accept
and produce these sometimes (e.g. Google Analytics cookies use them).
As a compromise, we now accept most control characters, but continue
to disallow NUL (\x00) and all whitespace (\t\n\r\f\v and space),
except that space and tab are allowed inside header values when
surrounded by non-whitespace characters.
Closes: gh-57, gh-58
> Allow more characters in header values

- h11/_abnf.py
- h11/_events.py
- h11/tests/test_events.py
- h11/tests/test_io.py
This constrains the matching to the printable ASCII characters that
are not the space ' ' character i.e. between '!' (65, 0x21) and '~'
(126, 0x7e). Doing so will mean that a request containing bytes
outside of this range will not match and instead raise an error.
This is based on my understanding of RFC 3986.
I think I've matched the style of the file, although I'm happy for this to be edited however to fit.
> Constrain regex request-target matching

- h11/_state.py
PyCharm has difficulty inspecting values that are both dynamically added to `__all__` and created via `globals()[x] = ...`. To the detriment of "only-update-one-place" I think it's valuable to have these values inspectable given how frequently they show up in a users codebase when using this library.
> Make all sentinel values inspectable by IDEs

- h11/tests/test_events.py
Let us see if oneliner is good enough. Issue #86
> Get value from exception to fix pytest 5 compat

- docs/source/api.rst
- h11/_connection.py
- h11/_headers.py
- h11/_readers.py
- h11/_writers.py
- h11/tests/test_connection.py
- h11/tests/test_events.py
- h11/tests/test_headers.py
- h11/tests/test_io.py
Closes #31
Based on #103, focusing on minimising benchmark regressions.
* Preserves HTTP header casing.
* `event.headers` is a sequence-like instance, containing two-tuples of bytes.
* `event.headers.raw_items()` is a list of two-tuples of `(raw_name, value)`.
Three benchmark runs here against each case.
7330.1 requests/sec
7357.9 requests/sec
7363.4 requests/sec
7310.5 requests/sec
7363.2 requests/sec
7354.3 requests/sec
7363.3 requests/sec
7321.4 requests/sec
7355.2 requests/sec
7353.7 requests/sec
7375.7 requests/sec
7352.6 requests/sec
7381.0 requests/sec
7410.0 requests/sec
7234.4 requests/sec
7274.0 requests/sec
7231.8 requests/sec
7272.5 requests/sec
7263.7 requests/sec
7268.9 requests/sec
7273.7 requests/sec
7022.7 requests/sec
7041.2 requests/sec
7052.2 requests/sec
7038.3 …
> Preserve header casing. Take two. 🎬

- h11/_headers.py
- h11/tests/test_headers.py
> Content length handling

- h11/_connection.py
- h11/_readers.py
- h11/_receivebuffer.py
- h11/tests/test_io.py
- h11/tests/test_receivebuffer.py
- newsfragments/7.feature.rst
Hello,
I want to submit a PR which closes https://github.com/python-hyper/h11/issues/7
According to [this](https://github.com/python-hyper/h11/issues/7#issuecomment-722464047) comment in the issue, there are problems with some old servers, which are not totally fit `HTTP/1.1` RFC. The original issue in `httpx` (https://github.com/encode/httpx/issues/1378) describes the situation, where some embedded system developers have to deal with a non-standard server
I tried to reimplement the function, which extracts headers for response, using regex
~Performance testing, fuzzing~
1. first of all it extracts part of `self._data` buffer until the `"\n\r?\n"`, which gives `data`
1. then it determines the line delimiter in `data` using `"\r?\n"` regex, which gives `delimiter`
1. then split lines using …
> Added ability to use LF, not only CRLF delimiter for response Headers and Body

- README.rst
- docs/source/index.rst
- newsfragments/114.removal.rst
- setup.py
- tox.ini
Following on from 4746b0a0fff341b70aaa4032b7fa49f613a1b586 Python 3.5
is not supported (has reached EoL) and 3.9 is (has been released).
> Clarify which Python versions are supported

- h11/_headers.py
- newsfragments/112.feature.rst
This is both in the docs (via the changelog) and by inheriting from
the Sequence ABC.
> Clarify that the Headers class is a Sequence

- h11/_connection.py
- h11/_events.py
- h11/tests/helpers.py
- h11/tests/test_connection.py
- h11/tests/test_events.py
- newsfragments/124.feature.rst
- setup.py
The _EventBundle used previously dynamically creates the Event
classes, which makes typing hard. As the Event classes are now stable
the dynamic creation isn't required, and as h11 supports Python3.6+
dataclasses can be used instead.
This now makes the Events frozen (and almost imutable) which better
matches the intended API. In turn it requires the `object.__setattr__`
usage and the alteration to the
`_clean_up_response_headers_for_sending` method.
This change also improves the performance a little, using the
benchmark,
Before: 6.7k requests/sec
After: 6.9k requests/sec
Notes:
The test response-header changes are required as the previous version
would mutate the response object.
The init for the Data event is required as slots and defaults aren't
possible with dataclasses.
> Switch event classes to dataclasses

- h11/_state.py
This is a minor change for a slightly more readable logs.
At the moment, when a protocol error is raised its traceback looks like: 
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>
During handling of the above exception, another exception occurred:
...
h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```
The `KeyError` at the top is just an implementation detail and does not need to be in tracebacks.
> Shorten traceback of protocol errors.

- h11/__init__.py
- h11/_connection.py
- h11/_headers.py
- h11/_readers.py
- h11/_receivebuffer.py
- h11/_state.py
- h11/_util.py
- h11/_writers.py
- h11/tests/helpers.py
- h11/tests/test_against_stdlib_http.py
- h11/tests/test_connection.py
- h11/tests/test_events.py
- h11/tests/test_headers.py
- h11/tests/test_helpers.py
- h11/tests/test_io.py
- h11/tests/test_receivebuffer.py
- h11/tests/test_state.py
- h11/tests/test_util.py
- setup.cfg
- setup.py
- tox.ini
This uses the same mypy settings as wsproto.
The Sentinel values are problematic, but I've found no good solution
that also has the property that type(Sentinel) is Sentinel - so this
should suffice for now.
Whilst I've been lazy with the tests, I've mostly avoided type ignores
in the main code. This should ensure that mypyc can be used if
desired.
> Add typing and enforce checking via tox/CI

- h11/_events.py
- h11/tests/test_events.py
We're currently validating the request target and raising a `LocalProtocolError` when it's invalid.
We ought to also extend this to the request method.
> Ensure request method is a valid token

- h11/_events.py
The standard is often interpreted as allowing any three digit status
code and hence h11 not supporting larger codes results in
incompatibities.
Fixes #134
> Expand the allowed status codes to 999

- .github/workflows/ci.yml
- README.rst
- docs/source/index.rst
- newsfragments/138.removal.rst
- setup.py
- tox.ini
Python 3.6 is at EOL and 3.10 was released around 2 months ago. This
allows the conditional dataclasses requirement to be removed.
> Change supported Python versions

- examples/trio-server.py
Remove an undocumented function call in `examples/trio-server.py`.
> Use `email.utils.format_datetime` instead of undocumented `wsgiref.handlers.format_date_time`

- examples/trio-server.py
See details:
[1] https://trio.readthedocs.io/en/latest/reference-io.html#trio.abc.SendStream.send_all
[2] https://h11.readthedocs.io/en/latest/api.html#h11.Connection.send_failed
> Call `conn.send_failed` if `stream.send_all` fails with an exception.

- examples/trio-server.py
Now trio 0.20.0 requires python 3.7 or later. But IMO it's not necessary to mention it here and update it every year.
> Remove python version in trio-server.py

- h11/_connection.py
Hi! I'm updating httpcore's type annotations (https://github.com/encode/httpcore/pull/526) to be compatible with the latest h11 version and encountering a difficulty with the type annotations on `next_event`. Since the return type includes `Sentinel` which is a private type in h11, the return type in httpcore cannot be defined correctly.
To resolve this, the `Sentinel` type could be exposed publicly. However, arbitrary sentinels cannot be handled by downstream libraries. Instead, they should have a well defined set of sentinels that they know to handle. `NEEDS_DATA` and `PAUSED` are already publicly exposed and are the two sentinel types that can be returned by `needs_data`. Narrowing the type definition to these specific types will confer to consumers that they should handle these …
> Update `next_event` annotation to reflect possible return types

- examples/trio-server.py
- h11/_connection.py
- h11/tests/test_connection.py
- h11/tests/test_io.py
The `black` version used in CI is not pinned so the new version's formatting needs to be applied to `master`.
> Format with black 23.3.0

- h11/_connection.py
I need this to not cast a lot of stuff on uvicorn. 🙏
> Add `@overload` to `Connection.send()`

- .github/workflows/ci.yml
- README.rst
- bench/benchmarks/benchmarks.py
- docs/source/conf.py
- docs/source/index.rst
- docs/source/make-state-diagrams.py
- examples/trio-server.py
- h11/_connection.py
- h11/_state.py
- h11/tests/test_against_stdlib_http.py
- h11/tests/test_connection.py
- setup.py
- tox.ini
The [second Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
Python 3.12.0 final is due out in two weeks: [2023-10-02](https://peps.python.org/pep-0693/).
See also https://dev.to/hugovk/help-test-python-312-beta-1508/
---
Python 3.7 is EOL and no longer receiving security updates (or any updates) from the core Python team.
| version |  released  |    eol     |
|:--------|:----------:|:----------:|
| 3.11    | 2022-10-24 | 2027-10-24 |
| …
> Add support for Python 3.11 and 3.12 and drop EOL 3.7

- h11/_connection.py
- h11/_events.py
- h11/tests/test_against_stdlib_http.py
- h11/tests/test_connection.py
- h11/tests/test_events.py
- h11/tests/test_helpers.py
- h11/tests/test_io.py
- pyproject.toml
- setup.cfg
- tox.ini
~I don't understand how master is passing...~
Master is passing because it passed 6 months ago, but dependencies changed, and something else also changed on the Python action, not sure what... 🤷 
Checklist
> Run format and mypy on Python 3.8

- h11/_state.py
When we try to switch protocols when the client has not requested it, h11 throws a `LocalProtocolError`.
Here is how h11 do it:
https://github.com/python-hyper/h11/blob/a2c68948accadc3876dffcf979d98002e4a4ed27/h11/_state.py#L284-L289
However, this exception can only be raised when the event is `_SWITCH_UPGRADE`, because another scenario was already checked here:
https://github.com/python-hyper/h11/blob/a2c68948accadc3876dffcf979d98002e4a4ed27/h11/_connection.py#L263-L268
In other words, if the server_switch_event is _SWITCH_CONNECT, we always know that such an event is being proposed.
> Fix _SWITCH_UPGRADE without proposal error message

- MANIFEST.in
In #159 the `h11/tests` directory was removed from wheels, but unfortunately it was also removed from sdists. This PR adds it back to sdists and maintains its absence in wheels.
``` shell
$ python -m build
$ tar -tf dist/h11-0.14.0+dev.tar.gz > 1.txt
$ git checkout add-tests-back
$ rm -rf *.egg-info
$ python -m build
$ tar -tf dist/h11-0.14.0+dev.tar.gz > 2.txt
$ diff -u 1.txt 2.txt
```
``` diff
@@ -45,8 +45,19 @@
h11-0.14.0+dev/h11/_writers.py
h11-0.14.0+dev/h11/py.typed
h11-0.14.0+dev/h11/tests/
+h11-0.14.0+dev/h11/tests/__init__.py
h11-0.14.0+dev/h11/tests/data/
h11-0.14.0+dev/h11/tests/data/test-file
+h11-0.14.0+dev/h11/tests/helpers.py
+h11-0.14.0+dev/h11/tests/test_against_stdlib_http.py
+h11-0.14.0+dev/h11/tests/test_connection.py
+h11-0.14.0+dev/h11/tests/test_events.py …
```
> Add `h11/tests` back to sdists

- h11/_headers.py
- h11/tests/test_headers.py
So there is this CVE on CPython https://www.cve.org/CVERecord?id=CVE-2020-10735, the problem is that parsing a base-10 integer with `int()` is quadratic. A rogue agent can forge a bad `Content-Length` header with a huge integer to DOS h11.
The way the bug was solved in CPython 3.11 was to verify the length of the `int` input, to make sure it stayed under a reasonable limit (4300 digits by default).
So using h11 with Py3.11, we get a `ValueError` when we try to parses a rogue Content-Length. But in Py3.8.2 (the lowest I have on my machine) it takes ages to parse it.
Consider the folowing example:
```py
import h11
conn = h11.Connection(h11.CLIENT)
conn.send(h11.Request(method="GET", target="/", headers=[("Host", "example.com")]))
conn.send(h11.EndOfMessage())
response = bytearray(b"HTTP/1.1 …
```
> Reject Content-Length longer than 1 billion TB

- docs/source/changes.rst
The previous link was to an unrelated change which fixed the Python 3.13 CI.
> Fix link to content-length limiting PR
